name: Grants Hub Client build and deploy to gh-pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install, Build, and Test 🔧
        env:
          REACT_APP_PINATA_JWT: ${{ secrets.REACT_APP_PINATA_JWT }}
          REACT_APP_PINATA_GATEWAY: ${{ secrets.REACT_APP_PINATA_GATEWAY }}
        run: |
          cd client
          yarn cache clean
          yarn install
          yarn lint
          yarn test
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: client/build # The folder the action should deploy.
