name: Grants Hub Client test and lint for PR
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install, Lint, and Test 🔧
        run: |
          cd client
          yarn install
          yarn lint
          yarn test